### PR TITLE
Example: fix marquee mobile height (fixes #155)

### LINKED ISSUE #155: (iOS/Safari) Section Marquee #6 height does not adjust to compensate text in mobile view
Correct:

section height does not adapt to text amount

Incorrect:
- Issue can also be reproduced on Mac (Chrome, Firefox, Safari) PC (Chrome, Firefox, Edge), iPad mini (Chrome, Firefox, Safari), and Android (Chrome, Firefox)
  screen shot 2016-10-17 at 2 16 04 pm

### PR DESCRIPTION
**Pull request by davidcalhoun**
# Before:

screen shot 2016-10-19 at 2 58 27 pm
# After:

screen shot 2016-10-19 at 2 58 42 pm

### CODE REVIEW

**Comment by jwijay** [comment]
I think the desired fix is to preserve the responsiveDropText behavior on mobile, for `justify=center` marquees, because `responsiveDropText={false}` seems to work correctly for marquees with `justify=center`.
screen shot 2016-10-28 at 6 42 44 am

**Comment by davidcalhoun** [comment]
Ah cool, thanks!  That does work a lot better - wasn't sure if the background was being changed out to something lighter.

I'll take another look and update this PR

**Comment by davidcalhoun** [comment]
@jwijay Appreciate you taking a look!

Should be fixed now - please have another look!

**Comment by jwijay** [comment]
LGTM. 👍 Tested in Safari, Chrome, Firefox, and IE11.

**Pull request merged**
